# @schema
# type: object
# required: true
# description: Plan to migrate virtual machines to migrate
# @schema
plan:
  # @schema
  # description: List of virtual machines to migrate
  # type: array
  # items:
  #   type: object
  #   required: [id, name]
  #   properties:
  #     id:
  #       type: string
  #       description: Id of the virtual machine to migrate
  #     name:
  #       type: string
  #       description: Name of the virtual machine to migrate
  # @schema
  vms:
    - id: "1"
      name: "test-migration-1"